# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-11 07:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import icf_career_fair.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_entity', '0009_auto_20210911_1304'),
        ('icf_item', '0012_auto_20190730_1158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFair',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icf_item.Item')),
                ('organiser_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organiser_contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mode_of_cf', models.CharField(choices=[(1, 'PRESENTIAL'), (2, 'VIRTUAL_CAREER_FAIR'), (3, 'HYBRID_CAREER_FAIR')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Career Fairs',
                'ordering': ['-created'],
            },
            bases=('icf_item.item',),
        ),
        migrations.CreateModel(
            name='CareerFairDraft',
            fields=[
                ('itemdraft_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icf_item.ItemDraft')),
                ('organiser_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organiser_contact_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('mode_of_cf', models.CharField(choices=[(1, 'PRESENTIAL'), (2, 'VIRTUAL_CAREER_FAIR'), (3, 'HYBRID_CAREER_FAIR')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Career Fair Drafts',
                'ordering': ['-created'],
            },
            bases=('icf_item.itemdraft',),
        ),
        migrations.CreateModel(
            name='CareerFairGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_fair_slug', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=icf_career_fair.models.upload_career_fair_media_location)),
                ('image_type', models.SmallIntegerField(choices=[(1, 'Hero'), (2, 'Gallery')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFair')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairGalleryOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_fair_slug', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=icf_career_fair.models.upload_career_fair_draft_media_location)),
                ('image_type', models.SmallIntegerField(choices=[(1, 'Hero'), (2, 'Gallery')], default=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFairDraft')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairMarkedForDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Deleted'), (3, 'Rejected')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_delete', to='icf_career_fair.CareerFair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('expiry', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('start_time', models.CharField(max_length=16)),
                ('end_time', models.CharField(max_length=16)),
                ('session_link', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_session', to='icf_career_fair.CareerFair')),
            ],
            options={
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('entity_name', models.CharField(max_length=80, verbose_name='entity_name')),
                ('position', models.CharField(max_length=80, verbose_name='position')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_speaker', to='icf_career_fair.CareerFair')),
            ],
            options={
                'verbose_name_plural': 'Speakers',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerAndSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.Session')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_speaker_profile_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=80, verbose_name='brand_name')),
                ('support_type', models.SmallIntegerField(choices=[(1, 'Partner'), (2, 'Sponsor'), (3, 'Gold Sponsor'), (4, 'Main Partner')], default=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_support', to='icf_career_fair.CareerFair')),
            ],
            options={
                'verbose_name_plural': 'Supports',
                'ordering': ['-created'],
            },
        ),
    ]
