# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import icf_career_fair.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('expiry', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('start_time', models.CharField(max_length=16)),
                ('end_time', models.CharField(max_length=16)),
                ('session_link', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_session', to='icf_career_fair.CareerFairDraft')),
            ],
            options={
                'verbose_name_plural': 'Draft Sessions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerAndSessionOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.SessionOptional')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('entity_name', models.CharField(max_length=80, verbose_name='entity_name')),
                ('position', models.CharField(max_length=80, verbose_name='position')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_speaker', to='icf_career_fair.CareerFairDraft')),
            ],
            options={
                'verbose_name_plural': 'Draft Speakers',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerProfileImageOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_speaker_profile_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.SpeakerOptional')),
            ],
        ),
        migrations.CreateModel(
            name='SupportOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=80, verbose_name='brand_name')),
                ('support_type', models.SmallIntegerField(choices=[(1, 'Partner'), (2, 'Sponsor'), (3, 'Gold Sponsor'), (4, 'Main Partner')], default=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cf_support', to='icf_career_fair.CareerFairDraft')),
            ],
            options={
                'verbose_name_plural': 'Draft Supports',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='speakerandsessionoptional',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.SpeakerOptional'),
        ),
    ]
