# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-23 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0002_auto_20210919_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfair',
            name='mode_of_cf',
            field=models.SmallIntegerField(choices=[(1, 'PRESENTIAL'), (2, 'VIRTUAL_CAREER_FAIR'), (3, 'HYBRID_CAREER_FAIR')], default=1),
        ),
    ]
