# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-26 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0005_auto_20210925_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='support_type',
            field=models.SmallIntegerField(choices=[(1, 'Partner'), (2, 'Sponsor'), (3, 'Gold Sponsor'), (4, 'Main Partner'), (5, 'Platinum Sponsor')], default=1),
        ),
    ]
