# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-27 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_orders', '0015_product_buyer_type'),
        ('icf_career_fair', '0006_auto_20210927_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.SmallIntegerField(choices=[(1, 'Individual'), (2, 'Entity'), (3, 'Sponsor')], default=1)),
                ('name_of_representative', models.CharField(blank=True, max_length=100, null=True, verbose_name='name_of_representative')),
                ('representative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAndProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('is_payment_successful', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.Participant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Product')),
            ],
        ),
    ]
