# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0008_auto_20210929_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFairAndProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sub_type', models.SmallIntegerField(choices=[(1, 'Ticket'), (2, 'Item For Sale'), (3, 'Advertisement'), (4, 'Other')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairAndProductOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sub_type', models.SmallIntegerField(choices=[(1, 'Ticket'), (2, 'Item For Sale'), (3, 'Advertisement'), (4, 'Other')], default=1)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFairDraft')),
            ],
        ),
    ]
