# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-29 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0017_productdraft'),
        ('icf_career_fair', '0009_careerfairandproduct_careerfairandproductoptional'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfairandproductoptional',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.ProductDraft'),
        ),
        migrations.AddField(
            model_name='careerfairandproduct',
            name='career_fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFair'),
        ),
        migrations.AddField(
            model_name='careerfairandproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Product'),
        ),
    ]
