# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0011_auto_20210929_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfairparticipant',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='careerfairandproduct',
            name='career_fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_products', to='icf_career_fair.CareerFair'),
        ),
        migrations.AlterField(
            model_name='careerfairandproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_products', to='icf_orders.Product'),
        ),
    ]
