# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0013_auto_20211004_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfair',
            name='end_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='careerfair',
            name='start_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='careerfairdraft',
            name='end_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='careerfairdraft',
            name='start_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
