# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-04 09:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0014_auto_20211004_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfairdraft',
            name='mode_of_cf',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'PRESENTIAL'), (2, 'VIRTUAL_CAREER_FAIR'), (3, 'HYBRID_CAREER_FAIR')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='careerfairdraft',
            name='organiser_contact_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
