# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0017_auto_20211020_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionoptional',
            name='career_fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_optional_sessions', to='icf_career_fair.CareerFairDraft'),
        ),
        migrations.AlterField(
            model_name='speakerandsessionoptional',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_sessions_optional', to='icf_career_fair.SessionOptional'),
        ),
        migrations.AlterField(
            model_name='speakerandsessionoptional',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_sessions_optional', to='icf_career_fair.SpeakerOptional'),
        ),
        migrations.AlterField(
            model_name='speakeroptional',
            name='career_fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_optional_speakers', to='icf_career_fair.CareerFairDraft'),
        ),
        migrations.AlterField(
            model_name='supportoptional',
            name='career_fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_fair_optional_supports', to='icf_career_fair.CareerFairDraft'),
        ),
    ]
