# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-25 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import icf_career_fair.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0021_auto_20211023_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_support_logo_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportLogoOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_support_optional_logo_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='sessionoptional',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='speaker_type',
        ),
        migrations.RemoveField(
            model_name='speakeroptional',
            name='speaker_type',
        ),
        migrations.AddField(
            model_name='speaker',
            name='speaker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='speakeroptional',
            name='speaker_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='speakerprofileimageoptional',
            name='image',
            field=models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_speaker_optional_profile_media_location, width_field='width'),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_type',
            field=models.CharField(max_length=80, verbose_name='support_type'),
        ),
        migrations.AlterField(
            model_name='supportoptional',
            name='support_type',
            field=models.CharField(max_length=80, verbose_name='support_type'),
        ),
        migrations.AddField(
            model_name='supportlogooptional',
            name='support',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.SupportOptional'),
        ),
        migrations.AddField(
            model_name='supportlogo',
            name='support',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.Support'),
        ),
    ]
