# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0022_auto_20211025_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='support_type_en',
            field=models.CharField(max_length=80, null=True, verbose_name='support_type'),
        ),
        migrations.AddField(
            model_name='support',
            name='support_type_es',
            field=models.CharField(max_length=80, null=True, verbose_name='support_type'),
        ),
        migrations.AddField(
            model_name='support',
            name='support_type_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='support_type'),
        ),
        migrations.AddField(
            model_name='supportoptional',
            name='support_type_en',
            field=models.CharField(max_length=80, null=True, verbose_name='support_type'),
        ),
        migrations.AddField(
            model_name='supportoptional',
            name='support_type_es',
            field=models.CharField(max_length=80, null=True, verbose_name='support_type'),
        ),
        migrations.AddField(
            model_name='supportoptional',
            name='support_type_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='support_type'),
        ),
    ]
