# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0023_auto_20211025_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerandsessionoptional',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_speakers_optional', to='icf_career_fair.SpeakerOptional'),
        ),
    ]
