# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-31 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import icf_career_fair.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0026_auto_20211029_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFairSpeakerDraftProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_career_fair_speaker_draft_profile_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairSpeakerProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_career_fair_speaker_profile_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('speaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairSupportDraftLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_career_fair_support_optional_logo_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.SupportOptional')),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairSupportLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_career_fair_support_logo_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.SupportOptional')),
            ],
        ),
    ]
