# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import icf_career_fair.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0027_careerfairspeakerdraftprofileimage_careerfairspeakerprofileimage_careerfairsupportdraftlogo_careerfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFairImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_career_fair_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFair')),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairImagesOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_career_fair_media_location, width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFairDraft')),
            ],
        ),
        migrations.AlterField(
            model_name='careerfairgalleryoptional',
            name='image',
            field=models.ImageField(upload_to=icf_career_fair.models.upload_career_fair_media_location),
        ),
        migrations.AlterField(
            model_name='supportlogo',
            name='logo',
            field=models.ImageField(height_field='height', upload_to=icf_career_fair.models.upload_career_fair_media_location, width_field='width'),
        ),
    ]
