# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-02 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0029_auto_20211101_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='speakeroptional',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='support',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='supportoptional',
            name='image_url',
        ),
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='speakeroptional',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='support',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='supportoptional',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image'),
        ),
    ]
