# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-02 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0030_auto_20211102_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='speakeroptional',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='speakerprofileimageoptional',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='supportoptional',
            old_name='image',
            new_name='image_url',
        ),
    ]
