# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-02 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0031_auto_20211102_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='image',
            new_name='image_url',
        ),
    ]
