# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0032_auto_20211102_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='speakeroptional',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='support',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='supportoptional',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='image'),
        ),
    ]
