# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-23 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0033_auto_20211102_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'Sessions'},
        ),
    ]
