# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-23 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0034_auto_20220523_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfair',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careerfair',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careerfairdraft',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='careerfairdraft',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionoptional',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionoptional',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
