# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-26 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0035_auto_20220523_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfair',
            name='timezone',
            field=models.CharField(default='nill', max_length=50),
        ),
    ]
