# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0036_careerfair_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_date_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
