# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-27 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0037_session_start_date_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerfairdraft',
            name='timezone',
            field=models.CharField(default='nill', max_length=50),
        ),
        migrations.AddField(
            model_name='sessionoptional',
            name='start_date_string',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
