# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-07 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0023_auto_20211111_2042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_entity', '0010_auto_20220522_2322'),
        ('icf_career_fair', '0038_auto_20220527_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFairAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='image')),
                ('ad_image_type', models.SmallIntegerField(choices=[(1, 'Mobile Image'), (2, 'Desktop Image')], default=2)),
                ('ad_redirect_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='image')),
                ('ad_status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Pending'), (4, 'Rejected')], default=3)),
                ('admin_comments', models.CharField(blank=True, max_length=1000, null=True, verbose_name='admin comments')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFair')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerFairAdvertisementViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image_type', models.SmallIntegerField(choices=[(1, 'Mobile Image'), (2, 'Desktop Image')], default=2)),
                ('number_of_views', models.PositiveIntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('career_fair_advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_career_fair.CareerFairAdvertisement')),
            ],
        ),
    ]
