# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_career_fair', '0040_auto_20220608_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerfairadvertisement',
            name='ad_image_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ad_image'),
        ),
        migrations.AlterField(
            model_name='careerfairadvertisement',
            name='ad_redirect_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ad_redirect'),
        ),
    ]
