# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_generic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMessagePerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Type')),
                ('perm_reqd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Messaging Permissions',
                'verbose_name_plural': 'Messaging Permissions',
            },
        ),
        migrations.CreateModel(
            name='ICFMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=120, verbose_name='subject')),
                ('topic_slug', models.SlugField()),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('sender_id', models.PositiveIntegerField(verbose_name='sender_id')),
                ('sender_name', models.CharField(max_length=80)),
                ('recipient_id', models.PositiveIntegerField()),
                ('recipient_name', models.CharField(max_length=80)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
                ('sender_archived', models.BooleanField(default=False, verbose_name='archived by sender')),
                ('recipient_archived', models.BooleanField(default=False, verbose_name='archived by recipient')),
                ('sender_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted by sender at')),
                ('recipient_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted by recipient at')),
                ('app_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Type')),
                ('entity_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_messages', to='icf_messages.ICFMessage', verbose_name='parent message')),
                ('recipient_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_type', to='contenttypes.ContentType')),
                ('sender_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_type', to='contenttypes.ContentType')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', to='icf_messages.ICFMessage', verbose_name='root message')),
            ],
            options={
                'verbose_name': 'message',
                'ordering': ['-sent_at', '-id'],
                'verbose_name_plural': 'messages',
            },
        ),
    ]
