# Generated by Django 3.2.14 on 2022-08-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_messages', '0006_auto_20201012_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='icfnotification',
            name='details_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='icfnotification',
            name='details_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='icfnotification',
            name='details_fr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='icfnotification',
            name='message_en',
            field=models.CharField(max_length=200, null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='icfnotification',
            name='message_es',
            field=models.CharField(max_length=200, null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='icfnotification',
            name='message_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='message'),
        ),
    ]
