# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_entity', '0001_initial'),
        ('icf_generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='icf_generic.Category'),
        ),
        migrations.AddField(
            model_name='entity',
            name='company_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='icf_entity.CompanySize'),
        ),
        migrations.AddField(
            model_name='entity',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='icf_entity.Industry'),
        ),
        migrations.AddField(
            model_name='entity',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='icf_entity.Sector'),
        ),
    ]
