# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_entity', '0003_auto_20181031_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysize',
            name='description_en',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='description_es',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='description_fr',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='size_en',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='size_es',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='size_fr',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
