# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0021_auto_20200121_1138'),
        ('icf_entity', '0006_auto_20181121_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryMasterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_type', models.CharField(max_length=500, verbose_name='ministry_type')),
                ('industries', models.CharField(max_length=500, verbose_name='industries')),
                ('sectors', models.CharField(max_length=500, verbose_name='sectors')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Country')),
            ],
            options={
                'verbose_name_plural': 'MinistryMasterConfig',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ministrymasterconfig',
            unique_together=set([('ministry_type', 'country')]),
        ),
    ]
