# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import icf_entity.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_entity', '0008_auto_20200521_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityBrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure_name', models.CharField(max_length=150)),
                ('brochure', models.FileField(blank=True, max_length=200, null=True, upload_to=icf_entity.models.upload_entity_brochure_media_location, validators=[icf_entity.models.validate_file_extension])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityPromotionalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotional_video_name', models.CharField(max_length=150)),
                ('promotional_video_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='schedule_appointment',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='entitypromotionalvideo',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity'),
        ),
        migrations.AddField(
            model_name='entitybrochure',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity'),
        ),
    ]
