# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_entity', '0009_auto_20210911_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'Active'), (3, 'Inactive')], default=2),
        ),
    ]
