# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:36
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import icf_generic.fields
import icf_jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_generic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=80, verbose_name='level')),
                ('level_en', models.CharField(max_length=80, null=True, verbose_name='level')),
                ('level_fr', models.CharField(max_length=80, null=True, verbose_name='level')),
                ('level_es', models.CharField(max_length=80, null=True, verbose_name='level')),
                ('desc', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'EducationLevels',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icf_item.Item')),
                ('experience_years', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40)])),
                ('experience_months', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salary_is_public', models.BooleanField(default=False)),
                ('open_positions', models.SmallIntegerField(default=1)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='icf_jobs.EducationLevel')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Jobs',
            },
            bases=('icf_item.item',),
        ),
        migrations.CreateModel(
            name='JobMarkedForDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Deleted'), (3, 'Rejected')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_delete', to='icf_jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobProfileFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_src', models.FileField(max_length=200, upload_to=icf_jobs.models.upload_job_profile_file_location, validators=[icf_jobs.models.validate_file_extension])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='icf_jobs.Job')),
            ],
            options={
                'verbose_name_plural': 'JobSkills',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=32, verbose_name='name')),
                ('job_type_en', models.CharField(max_length=32, null=True, verbose_name='name')),
                ('job_type_fr', models.CharField(max_length=32, null=True, verbose_name='name')),
                ('job_type_es', models.CharField(max_length=32, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'JobTypes',
            },
        ),
        migrations.CreateModel(
            name='JobUserApplied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(2, 'Maybe'), (3, 'Yes'), (4, 'NO')], default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'JobsUserApplied',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('name_en', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=120, null=True, verbose_name='name')),
                ('desc', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Occupations',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=50, verbose_name='relation')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Relationships',
            },
        ),
        migrations.CreateModel(
            name='SalaryFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=40, verbose_name='salary frequency')),
                ('frequency_en', models.CharField(max_length=40, null=True, verbose_name='salary frequency')),
                ('frequency_fr', models.CharField(max_length=40, null=True, verbose_name='salary frequency')),
                ('frequency_es', models.CharField(max_length=40, null=True, verbose_name='salary frequency')),
                ('desc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SalaryFrequencies',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='skill')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='skill')),
                ('name_fr', models.CharField(max_length=200, null=True, verbose_name='skill')),
                ('name_es', models.CharField(max_length=200, null=True, verbose_name='skill')),
                ('skill_type', models.CharField(choices=[('key_skill', 'key skills'), ('computer_skill', 'computer skills'), ('language', 'language skills')], max_length=50, verbose_name='skill type')),
            ],
            options={
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30, verbose_name='school')),
                ('from_year', models.PositiveIntegerField()),
                ('to_year', models.PositiveIntegerField()),
                ('certification', models.CharField(max_length=30, verbose_name='certification')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.EducationLevel')),
            ],
            options={
                'verbose_name_plural': 'UserEducation',
            },
        ),
        migrations.CreateModel(
            name='UserJobProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_bio', models.CharField(blank=True, max_length=250, null=True, verbose_name='professional biography')),
                ('has_experience', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('entity', models.CharField(max_length=200, verbose_name='entity')),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.UserJobProfile')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.Relationship')),
            ],
            options={
                'verbose_name_plural': 'UserReferences',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.UserJobProfile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.Skill')),
            ],
            options={
                'verbose_name_plural': 'UserSkills',
            },
        ),
        migrations.CreateModel(
            name='UserWorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250, verbose_name='job title')),
                ('worked_from', icf_generic.fields.ICFApproxDateField()),
                ('worked_till', icf_generic.fields.ICFApproxDateField()),
                ('entity', models.CharField(max_length=200, verbose_name='entity')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.UserJobProfile')),
            ],
            options={
                'verbose_name_plural': 'UserWorkExperience',
            },
        ),
        migrations.AddField(
            model_name='usereducation',
            name='job_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.UserJobProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('name', 'skill_type')]),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='icf_jobs.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='icf_jobs.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='icf_jobs.Occupation'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='icf_generic.Currency'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='icf_jobs.SalaryFrequency'),
        ),
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set([('job_profile', 'skill')]),
        ),
    ]
