# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 14:04
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

from icf_entity.models import Entity
from icf_jobs.models import JobPerms


def add_entity_permissions(apps, schema_editor):
    #content_type = ContentType.objects.get(app_label='icf_entity', model='entity')
    content_type = ContentType.objects.get_for_model(Entity)
    Permission.objects.get_or_create(codename=JobPerms.JOB_CREATE, name='Create Job for the Entity', content_type=content_type)
    Permission.objects.get_or_create(codename=JobPerms.JOB_PUBLISH, name='Publish Job for the Entity', content_type=content_type)
    Permission.objects.get_or_create(codename=JobPerms.JOB_RECRUIT, name='Recruit Job applicants for the Entity', content_type=content_type)
    Permission.objects.get_or_create(codename=JobPerms.JOB_ADMIN, name='Admin for Entity Jobs', content_type=content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0001_initial'),
        ('icf_entity', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_entity_permissions)
    ]
