# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0002_entity_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='description_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='description_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='description_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='relation_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='relation'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='relation_es',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='relation'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='relation_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='relation'),
        ),
    ]
