# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0005_jobdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkillOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.Job')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.Skill')),
            ],
            options={
                'verbose_name_plural': 'JobSkills',
            },
        ),
    ]
