# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0006_jobskilloptional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobskilloptional',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.JobDraft'),
        ),
    ]
