# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0007_auto_20181122_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobskilloptional',
            options={'verbose_name_plural': 'JobSkillsOptional'},
        ),
        migrations.AlterField(
            model_name='jobskilloptional',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_optional_skills', to='icf_jobs.JobDraft'),
        ),
        migrations.AlterField(
            model_name='jobskilloptional',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_optional_skills', to='icf_jobs.Skill'),
        ),
    ]
