# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0008_auto_20181122_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdraft',
            name='open_positions',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
