# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0009_auto_20181123_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='external_website_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdraft',
            name='external_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdraft',
            name='external_website_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
