# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 10:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import icf_jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0010_auto_20190521_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredUserFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('resume_src', models.FileField(max_length=200, upload_to=icf_jobs.models.upload_job_profile_file_location, validators=[icf_jobs.models.validate_file_extension])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
