# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-11 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0013_auto_20190911_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkexperience',
            name='entity',
        ),
    ]
