# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0014_remove_userworkexperience_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkexperience',
            name='entity',
            field=models.CharField(default=1, max_length=200, verbose_name='entity'),
            preserve_default=False,
        ),
    ]
