# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-18 09:19
from __future__ import unicode_literals

from django.db import migrations
import icf_generic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0015_userworkexperience_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='end_date',
            field=icf_generic.fields.ICFApproxDateField(),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='start_date',
            field=icf_generic.fields.ICFApproxDateField(),
        ),
    ]
