# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0017_userresume_userresumecomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresumecomponent',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userresume',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
