# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0018_auto_20190927_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobuserapplied',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.UserResume'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
    ]
