# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0019_auto_20191015_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobprofile',
            name='pro_bio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='professional biography'),
        ),
        migrations.AlterField(
            model_name='userresume',
            name='biography',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='biography'),
        ),
    ]
