# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-19 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0020_auto_20191113_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresumecomponent',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
