# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0022_auto_20191210_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter_email_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdraft',
            name='recruiter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobdraft',
            name='recruiter_email_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
