# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-21 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_jobs', '0024_candidatesearchforjobmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('entity_slug', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('work_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=500, null=True)),
                ('key_skill', models.CharField(blank=True, max_length=500, null=True)),
                ('computer_skill', models.CharField(blank=True, max_length=500, null=True)),
                ('language_skill', models.CharField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
