# Generated by Django 3.2.14 on 2022-08-25 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0026_auto_20200903_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreference',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender', models.CharField(max_length=200, verbose_name='recommender')),
                ('recommender_email', models.CharField(max_length=100, verbose_name='email')),
                ('desc', models.CharField(max_length=80)),
                ('status', models.SmallIntegerField(default=1)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.relationship')),
            ],
            options={
                'verbose_name_plural': 'UserRecommendation',
            },
        ),
        migrations.CreateModel(
            name='UserExtraCurricularActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitiy', models.CharField(max_length=500, verbose_name='activities')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserExtraCurricularActivities',
            },
        ),
    ]
