# Generated by Django 3.2.14 on 2022-08-30 19:51

from django.db import migrations, models
import django.db.models.deletion
import icf_generic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0030_userlicensecertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('instructor', models.CharField(blank=True, max_length=250, null=True, verbose_name='instructor')),
                ('completed_on', icf_generic.fields.ICFApproxDateField()),
                ('length', models.IntegerField(verbose_name='length')),
                ('duration', models.SmallIntegerField(choices=[(1, 'Minutes'), (2, 'Hours'), (3, 'Days')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserCourse',
            },
        ),
    ]
