# Generated by Django 3.2.14 on 2022-09-01 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0033_auto_20220901_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserInterviewQuestions',
            },
        ),
    ]
