# Generated by Django 3.2.14 on 2022-09-01 09:37

from django.db import migrations, models
import django.db.models.deletion
import icf_generic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0034_userinterviewquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfessionalMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('Body', models.CharField(blank=True, max_length=250, null=True, verbose_name='body')),
                ('description', models.TextField(max_length=50000, verbose_name='description')),
                ('membership_level', models.SmallIntegerField(choices=[(1, 'Associate Member'), (2, 'Moderator')], default=1)),
                ('joined_on', icf_generic.fields.ICFApproxDateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserProfessionalMemberships',
            },
        ),
    ]
