# Generated by Django 3.2.14 on 2022-09-03 20:09

from django.db import migrations, models
import django.db.models.deletion
import icf_generic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0021_auto_20200121_1138'),
        ('icf_jobs', '0035_userprofessionalmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userawardrecognition',
            name='award_institution',
            field=models.CharField(max_length=500, verbose_name='award_institution'),
        ),
        migrations.AlterField(
            model_name='userawardrecognition',
            name='award_level',
            field=models.SmallIntegerField(choices=[(1, 'Nominated'), (2, 'Awarded')], default=1),
        ),
        migrations.CreateModel(
            name='UserVolunteering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('description', models.TextField(max_length=50000, verbose_name='description')),
                ('staff_level', models.SmallIntegerField(choices=[(1, 'Management'), (2, 'Moderator')], default=1)),
                ('role', models.CharField(max_length=500, verbose_name='role')),
                ('start_date', icf_generic.fields.ICFApproxDateField()),
                ('end_date', icf_generic.fields.ICFApproxDateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.city')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserVolunteerings',
            },
        ),
    ]
