# Generated by Django 3.2.14 on 2022-09-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0036_auto_20220903_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrelevantlink',
            name='relevant_link',
        ),
        migrations.AddField(
            model_name='userrelevantlink',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userrelevantlink',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='userrelevantlink',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
        migrations.CreateModel(
            name='UserVisionMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(max_length=50000, verbose_name='vision')),
                ('mission', models.TextField(max_length=50000, verbose_name='mission')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserVisionMissions',
            },
        ),
        migrations.CreateModel(
            name='UserPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='title')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserPublications',
            },
        ),
        migrations.CreateModel(
            name='UserInfluencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='title')),
                ('url', models.CharField(max_length=500, verbose_name='url')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserInfluencers',
            },
        ),
    ]
