# Generated by Django 3.2.14 on 2022-09-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_entity', '0010_auto_20220522_2322'),
        ('icf_generic', '0021_auto_20200121_1138'),
        ('icf_jobs', '0037_auto_20220904_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferedWorkSiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Onsite'), (2, 'Remote'), (3, 'Hyrbrid')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserPreferedWorkSiteTypes',
            },
        ),
        migrations.CreateModel(
            name='UserPreferedWage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPreferedWage', to='icf_generic.currency')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPreferedWage', to='icf_jobs.salaryfrequency')),
            ],
            options={
                'verbose_name_plural': 'UserPreferedWages',
            },
        ),
        migrations.CreateModel(
            name='UserPreferedJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(1, 'Full time'), (2, 'Contract'), (3, 'Part time')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserPreferedJobTypes',
            },
        ),
        migrations.CreateModel(
            name='UserPreferedJobStaffLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_level', models.SmallIntegerField(choices=[(1, 'Management'), (2, 'Junior'), (3, 'Executive'), (4, 'Senior')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserPreferedJobStaffLevels',
            },
        ),
        migrations.CreateModel(
            name='UserPreferedIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPreferedIndustries', to='icf_entity.industry')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserPreferedIndustries',
            },
        ),
        migrations.CreateModel(
            name='UserPreferedFunctionalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPreferedFunctionalArea', to='icf_entity.sector')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserPreferedFunctionalAreas',
            },
        ),
        migrations.CreateModel(
            name='UserPreferedCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPreferedCountry', to='icf_generic.country')),
                ('job_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_jobs.userjobprofile')),
            ],
            options={
                'verbose_name_plural': 'UserPreferedCountry',
            },
        ),
    ]
