# Generated by Django 3.2.14 on 2022-10-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_jobs', '0038_userpreferedcountry_userpreferedfunctionalarea_userpreferedindustry_userpreferedjobstafflevel_userpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesearch',
            name='functional_area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidatesearch',
            name='industries',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidatesearch',
            name='job_level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidatesearch',
            name='salary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidatesearch',
            name='worksite_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
