# Generated by Django 3.2.14 on 2022-08-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_generic', '0021_auto_20200121_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Draft'), (2, 'Active'), (3, 'Closed')], null=True)),
                ('url', models.CharField(max_length=170, verbose_name='url')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.type')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.language')),
            ],
            options={
                'verbose_name_plural': 'Announcement',
                'ordering': ['-created'],
            },
        ),
    ]
