# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 11:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import icf_featuredevents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('sub_title', models.CharField(max_length=250, verbose_name='sub_title')),
                ('sub_title_en', models.CharField(max_length=250, null=True, verbose_name='sub_title')),
                ('sub_title_fr', models.CharField(max_length=250, null=True, verbose_name='sub_title')),
                ('sub_title_es', models.CharField(max_length=250, null=True, verbose_name='sub_title')),
                ('image', models.ImageField(upload_to=icf_featuredevents.models.upload_featured_event_media_location)),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=2)),
                ('location', models.CharField(max_length=70, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('start_date_timing', models.CharField(blank=True, max_length=50, verbose_name='start date timing')),
                ('end_date_timing', models.CharField(blank=True, max_length=50, verbose_name='end date timing')),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_featured_event', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('contact_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedEventAndCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedEventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedEventGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=150, null=True, verbose_name='title')),
                ('image_1', models.ImageField(upload_to=icf_featuredevents.models.upload_featured_event_media_location)),
                ('image_2', models.ImageField(upload_to=icf_featuredevents.models.upload_featured_event_media_location)),
                ('image_3', models.ImageField(upload_to=icf_featuredevents.models.upload_featured_event_media_location)),
                ('image_4', models.ImageField(upload_to=icf_featuredevents.models.upload_featured_event_media_location)),
                ('gallery_url', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('entity_name', models.CharField(max_length=100, verbose_name='entity name')),
                ('entity_email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('name_of_representative', models.CharField(max_length=100, verbose_name='name_of_representative')),
                ('address', models.CharField(max_length=500, verbose_name='address')),
                ('participants', models.CharField(max_length=10000, verbose_name='participants')),
                ('is_payment_successful', models.BooleanField(default=False)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('featured_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.FeaturedEvent')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_type', models.CharField(max_length=150, verbose_name='participation type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
                ('is_active', models.BooleanField(default=False)),
                ('does_have_extra_participants', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='currency')),
                ('no_of_tickets_allowed', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.FeaturedEventCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('description_fr', models.TextField(null=True, verbose_name='description')),
                ('description_es', models.TextField(null=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.Product'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featuredeventandcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.FeaturedEventCategory'),
        ),
        migrations.AddField(
            model_name='featuredeventandcategory',
            name='featured_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.FeaturedEvent'),
        ),
        migrations.AddField(
            model_name='featuredeventandcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.Product'),
        ),
        migrations.AddField(
            model_name='featuredevent',
            name='terms_and_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.TermsAndConditions'),
        ),
    ]
