# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_featuredevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_this_extra_participant_type',
            field=models.BooleanField(default=False),
        ),
    ]
