# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_featuredevents', '0002_product_is_this_extra_participant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_this_extra_participant_type',
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.Product'),
        ),
    ]
