# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_featuredevents', '0003_auto_20190308_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.Product'),
        ),
    ]
