# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_featuredevents', '0004_auto_20190311_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField(verbose_name='expiry date')),
                ('does_have_extra_participants', models.BooleanField(default=False)),
                ('no_of_tickets_allowed', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.FeaturedEventCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
        migrations.AlterField(
            model_name='featuredeventandcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.EventProduct'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.EventProduct'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
