# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0001_initial'),
        ('icf_featuredevents', '0006_auto_20190715_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedEventAndCategory',
        ),
        migrations.DeleteModel(
            name='FeaturedEventCategory',
        ),
        migrations.AddField(
            model_name='eventproduct',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredeventandproduct',
            name='featured_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.FeaturedEvent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredeventandproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='icf_featuredevents.EventProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
