# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-01 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_featuredevents', '0007_auto_20190715_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredevent',
            name='email_content',
            field=models.TextField(default='', verbose_name='email_content'),
        ),
    ]
