# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-05 07:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_featuredevents', '0009_auto_20201101_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='entity_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='entity_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='entity name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name_of_representative',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name_of_representative'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participants',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_no',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
