# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 10:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import icf_events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_entity', '0006_auto_20181121_1832'),
        ('icf_item', '0010_auto_20190716_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icf_item.Item')),
                ('registration_website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-created'],
            },
            bases=('icf_item.item',),
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_slug', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('hero_image', models.ImageField(upload_to=icf_events.models.upload_event_media_location)),
                ('image_1', models.ImageField(upload_to=icf_events.models.upload_event_media_location)),
                ('image_2', models.ImageField(upload_to=icf_events.models.upload_event_media_location)),
                ('image_3', models.ImageField(upload_to=icf_events.models.upload_event_media_location)),
                ('image_4', models.ImageField(upload_to=icf_events.models.upload_event_media_location)),
                ('is_hero_image', models.BooleanField(default=False)),
                ('gallery_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_events.Event')),
            ],
        ),
    ]
