# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 14:04
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

from icf_entity.models import Entity
from icf_events.models import EventPerms


def add_entity_permissions(apps, schema_editor):
    #content_type = ContentType.objects.get(app_label='icf_entity', model='entity')
    content_type = ContentType.objects.get_for_model(Entity)
    Permission.objects.get_or_create(codename=EventPerms.EVENT_CREATE, name='Create Event for the Entity', content_type=content_type)
    Permission.objects.get_or_create(codename=EventPerms.EVENT_PUBLISH, name='Publish Event for the Entity', content_type=content_type)
    Permission.objects.get_or_create(codename=EventPerms.EVENT_ADMIN, name='Admin for Entity Events', content_type=content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('icf_events', '0001_initial'),
        ('icf_entity', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_entity_permissions)
    ]
