# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-28 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_events', '0004_eventdraft_eventgalleryoptional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='daily_end_time',
            field=models.CharField(default='7 am', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='daily_start_time',
            field=models.CharField(default='7 am', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='daily_end_time',
            field=models.CharField(default='6 pm', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdraft',
            name='daily_start_time',
            field=models.CharField(default='7 am', max_length=16),
            preserve_default=False,
        ),
    ]
