# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 06:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_events', '0005_auto_20190828_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdraft',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='eventdraft',
            name='contact_no',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='eventdraft',
            name='daily_end_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='eventdraft',
            name='daily_start_time',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='eventdraft',
            name='registration_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
