# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import icf_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_events', '0006_auto_20190829_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='gallery_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_media_location),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_media_location),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_media_location),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_media_location),
        ),
        migrations.AlterField(
            model_name='eventgallery',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='gallery_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_draft_media_location),
        ),
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_draft_media_location),
        ),
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_draft_media_location),
        ),
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=icf_events.models.upload_event_draft_media_location),
        ),
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='title'),
        ),
    ]
