# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_events', '0008_auto_20190829_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventgallery',
            old_name='hero_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='gallery_url',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='is_hero_image',
        ),
        migrations.RemoveField(
            model_name='eventgallery',
            name='title',
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='image_type',
            field=models.SmallIntegerField(choices=[(1, 'Hero'), (2, 'Gallery')], default=2),
        ),
    ]
