# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import icf_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_events', '0011_auto_20190830_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='image',
            field=models.ImageField(upload_to=icf_events.models.upload_event_draft_media_location),
        ),
    ]
