# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-30 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import icf_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_events', '0012_auto_20190830_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgalleryoptional',
            name='image',
            field=models.ImageField(upload_to=icf_events.models.upload_event_media_location),
        ),
    ]
