# Generated by Django 3.2.14 on 2022-10-13 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_events', '0013_auto_20190830_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('entity_slug', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('work_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=500, null=True)),
                ('key_skill', models.CharField(blank=True, max_length=500, null=True)),
                ('computer_skill', models.CharField(blank=True, max_length=500, null=True)),
                ('language_skill', models.CharField(blank=True, max_length=500, null=True)),
                ('job_title', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('functional_area', models.CharField(blank=True, max_length=500, null=True)),
                ('industries', models.CharField(blank=True, max_length=500, null=True)),
                ('job_level', models.CharField(blank=True, max_length=500, null=True)),
                ('worksite_type', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
