# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_entity', '0006_auto_20181121_1832'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('icf_generic', '0016_auto_20190624_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionAndSubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_limit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_credits', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product_item_id', models.IntegerField(blank=True, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_email', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('name_of_representative', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('participants', models.CharField(blank=True, max_length=500, null=True)),
                ('feature_event_slug', models.CharField(blank=True, max_length=200, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='CountryTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CreditAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('action_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('action_desc_en', models.CharField(blank=True, max_length=100, null=True)),
                ('action_desc_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('action_desc_es', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_required', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Type')),
            ],
        ),
        migrations.CreateModel(
            name='CreditDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Type')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('debits', models.IntegerField(default=0)),
                ('available_credits', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_orders.CreditAction')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='CreditInvoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transaction', models.IntegerField()),
                ('gateway', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ICFPaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.SlugField(blank=True, unique=True)),
                ('payment_type', models.CharField(choices=[(1, 'PAYMENT_TYPE_STRIPE'), (2, 'PAYMENT_TYPE_PAYPAL'), (3, 'PAYMENT_TYPE_OFFLINE')], max_length=2)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
                ('req_amount_in_cents', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('req_amount_in_dollars', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('req_token', models.CharField(max_length=150)),
                ('req_desc', models.CharField(max_length=500)),
                ('resp_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[(1, 'SUCCESS'), (2, 'PENDING'), (3, 'ERROR'), (4, 'FAILURE')], default=4, max_length=2)),
                ('resp_error_code', models.CharField(blank=True, max_length=150, null=True)),
                ('resp_error_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('resp_amount_in_cents', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('resp_amount_in_dollars', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('resp_transaction_id', models.CharField(blank=True, max_length=500, null=True)),
                ('resp_currency', models.CharField(blank=True, max_length=100, null=True)),
                ('resp_failure_code', models.CharField(blank=True, max_length=100, null=True)),
                ('resp_failure_message', models.CharField(blank=True, max_length=200, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_order_details', to='contenttypes.ContentType')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_order', to='icf_entity.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_type', models.SmallIntegerField(choices=[(1, 'SUBSCRIPTION'), (2, 'CREDIT'), (3, 'EVENT_PRODUCT'), (4, 'OTHER')], default=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Currency')),
                ('parent_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_count', models.IntegerField(default=0)),
                ('max_count', models.IntegerField(null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.CreditAction')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_details',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_product', to='icf_orders.Product'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.ICFPaymentTransaction'),
        ),
        migrations.AddField(
            model_name='countrytax',
            name='tax_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.TaxType'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionandsubscriptionplan',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.CreditAction'),
        ),
        migrations.AddField(
            model_name='actionandsubscriptionplan',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.SubscriptionPlan'),
        ),
    ]
