# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0002_auto_20190716_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
