# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 09:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0006_auto_20190718_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='billingEmail',
            field=models.EmailField(default='aa@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='entityPhone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
