# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0007_auto_20190719_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='feature_event_slug',
            new_name='featured_event_slug',
        ),
    ]
