# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0008_auto_20190719_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icfpaymenttransaction',
            name='req_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='icfpaymenttransaction',
            name='req_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
