# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_orders', '0009_auto_20190719_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
