# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0010_orderdetails_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionaction',
            unique_together=set([('subscription', 'action')]),
        ),
    ]
