# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_entity', '0009_auto_20210911_1304'),
        ('icf_orders', '0013_auto_20190724_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='icf_entity.Entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.SmallIntegerField(choices=[(1, 'SUBSCRIPTION'), (2, 'CREDIT'), (3, 'EVENT_PRODUCT'), (4, 'CAREER_FAIR_PRODUCT'), (5, 'OTHER')], default=3),
        ),
    ]
