# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0014_auto_20210911_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer_type',
            field=models.SmallIntegerField(choices=[(1, 'Individual'), (2, 'Entity'), (3, 'Sponsor'), (4, 'Other')], default=1),
        ),
    ]
