# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0015_product_buyer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
