# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0020_auto_20211005_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='career_fair_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
