# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-11 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0022_cart_product_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icfpaymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[(1, 'PAYMENT_TYPE_STRIPE'), (2, 'PAYMENT_TYPE_PAYPAL'), (3, 'PAYMENT_TYPE_OFFLINE'), (4, 'PAYMENT_TYPE_FREE_CHECKOUT')], max_length=2),
        ),
    ]
