# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-20 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_orders', '0023_auto_20211111_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icfpaymenttransaction',
            name='payment_status',
            field=models.CharField(choices=[('1', 'SUCCESS'), ('2', 'PENDING'), ('3', 'ERROR'), ('4', 'FAILURE')], default=4, max_length=2),
        ),
        migrations.AlterField(
            model_name='icfpaymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('1', 'PAYMENT_TYPE_STRIPE'), ('2', 'PAYMENT_TYPE_PAYPAL'), ('3', 'PAYMENT_TYPE_OFFLINE'), ('4', 'PAYMENT_TYPE_FREE_CHECKOUT')], max_length=2),
        ),
    ]
