# Generated by Django 3.2.14 on 2022-10-21 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_entity', '0010_auto_20220522_2322'),
        ('icf_generic', '0021_auto_20200121_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icf_orders', '0024_auto_20220620_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_type', models.CharField(choices=[('1', 'WITHDRAWAL_TYPE_ACCOUNT'), ('2', 'WITHDRAWAL_TYPE_MM')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('1', 'SUCCESS'), ('2', 'PENDING'), ('3', 'ERROR'), ('4', 'FAILURE')], default=4, max_length=2)),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_country', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_branch_code', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_key', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_swift', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_IBAN', models.CharField(blank=True, max_length=100, null=True)),
                ('mm_account', models.CharField(blank=True, max_length=100, null=True)),
                ('mm_account_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('mm_account_country', models.CharField(blank=True, max_length=100, null=True)),
                ('mm_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank='$', max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.city')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_entity.entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='icf_entity.entity')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('withdrals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_orders.withdrawaltransaction')),
            ],
        ),
    ]
