# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0003_auto_20181114_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_es',
            field=models.CharField(max_length=20, null=True, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_fr',
            field=models.CharField(max_length=20, null=True, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_es',
            field=models.CharField(max_length=20, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_fr',
            field=models.CharField(max_length=20, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
