# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0004_auto_20181119_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressOptional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=300, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=300, verbose_name='address continued')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.City')),
            ],
        ),
    ]
