# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0008_auto_20181122_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=2000, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.CharField(max_length=2000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=models.CharField(max_length=2000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_fr',
            field=models.CharField(max_length=2000, null=True, verbose_name='answer'),
        ),
    ]
