# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0010_auto_20181204_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredvideo',
            name='video_url_en',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='featuredvideo',
            name='video_url_es',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='featuredvideo',
            name='video_url_fr',
            field=models.URLField(null=True),
        ),
    ]
