# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0011_auto_20181212_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='name_es',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='name_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

