# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0013_auto_20190508_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='video_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='video_url'),
        ),
        migrations.AddField(
            model_name='faq',
            name='video_url_es',
            field=models.URLField(blank=True, null=True, verbose_name='video_url'),
        ),
        migrations.AddField(
            model_name='faq',
            name='video_url_fr',
            field=models.URLField(blank=True, null=True, verbose_name='video_url'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=2000, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(max_length=2000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(max_length=2000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(max_length=2000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='video_url'),
        ),
    ]
