# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0014_auto_20190517_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=10000, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(max_length=10000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(max_length=10000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(max_length=10000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'job_seekers'), (1, 'professional'), (3, 'entities'), (4, 'general')], null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=5000, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=5000, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=5000, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=5000, null=True, verbose_name='question'),
        ),
    ]
