# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0015_auto_20190624_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(max_length=50000, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(max_length=50000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(max_length=50000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(max_length=50000, null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=10000, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=10000, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_es',
            field=models.CharField(max_length=10000, null=True, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(max_length=10000, null=True, verbose_name='question'),
        ),
    ]
