# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0016_auto_20190624_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.SmallIntegerField(choices=[(1, 'HOME_OR_WORK'), (2, 'BILLING')], default=1),
        ),
    ]
