# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-10 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0017_address_address_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_fr', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('name_es', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('description_fr', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('description_es', models.CharField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.FAQCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='faq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.FAQ'),
        ),
    ]
