# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-11 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0018_auto_20191210_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questioncategory',
            unique_together=set([('category', 'faq')]),
        ),
    ]
