# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-21 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_generic', '0020_auto_20191211_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_es',
            field=models.CharField(max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='name'),
        ),
    ]
