# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_auth', '0002_auto_20181031_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('os', models.CharField(max_length=200)),
                ('device_type', models.CharField(max_length=300)),
                ('device_info', models.CharField(max_length=300)),
                ('browser', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
