# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icf_auth', '0004_userprofile_is_profile_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_profile_public',
            new_name='is_profile_private',
        ),
    ]
