# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-29 10:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_auth', '0005_auto_20190702_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEmailOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('mobile', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('key', models.CharField(max_length=16)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Sent'), (3, 'Verified'), (3, 'Failed')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
