# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-10 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_auth', '0006_registrationemailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationemailotp',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Sent'), (3, 'Verified'), (4, 'Failed')]),
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Created'), (2, 'Sent'), (3, 'Verified'), (4, 'Failed')]),
        ),
    ]
