# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_entity', '0001_initial'),
        ('icf_generic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('title_en', models.CharField(max_length=80, null=True, verbose_name='title')),
                ('title_fr', models.CharField(max_length=80, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=80, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('description_en', models.CharField(max_length=1000, null=True, verbose_name='description')),
                ('description_fr', models.CharField(max_length=1000, null=True, verbose_name='description')),
                ('description_es', models.CharField(max_length=1000, null=True, verbose_name='description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Active'), (3, 'Expired'), (4, 'Closed'), (5, 'Marked for delete'), (6, 'Deleted')], default=1)),
                ('expiry', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='icf_generic.Category')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_entity.Entity')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='icf_generic.Type')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='icf_generic.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemUserView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_view', to='icf_item.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_item', to='icf_item.Item'),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
