# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_en',
            field=models.CharField(max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_es',
            field=models.CharField(max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_fr',
            field=models.CharField(max_length=2000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
