# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icf_item', '0004_itemdraft'),
        ('icf_generic', '__latest__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdraft',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icf_generic.AddressOptional'),
        ),
    ]
