# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_item', '0007_auto_20181122_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdraft',
            name='description_en',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='description_es',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='description_fr',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='title_es',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemdraft',
            name='title_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
    ]
