# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icf_item', '0011_auto_20190729_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdraft',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemdraft',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemdraft',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='itemdraft',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
