# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-11 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icf_generic', '0021_auto_20200121_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCompensationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name_es', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('description_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('description_es', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'CurrentCompensationStatuses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CurrentWorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name_es', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('description_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('description_es', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'CurrentWorkStatuses',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EGSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name_fr', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name_es', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('description_fr', models.CharField(blank=True, max_length=500, null=True)),
                ('description_es', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'EGSectors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserWorkStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_generic.Country')),
                ('current_compensation_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_covid_status.CurrentCompensationStatus')),
                ('current_work_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_covid_status.CurrentWorkStatus')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icf_covid_status.EGSector')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
